# Generated by Django 4.1.7 on 2023-03-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=130)),
                ('address', models.CharField(max_length=300)),
                ('number_of_properties_sold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('250 SQM Lifecamp 1', '250 SQM Lifecamp 1'), ('300 SQM Lifecamp 1', '300 SQM Lifecamp 1'), ('500 SQM Lifecamp 1', '500 SQM Lifecamp 1'), ('750 SQM Lifecamp 1', '500 SQM Lifecamp 1'), ('4 Bedroom FD Lifecamp 1', '4 BD fully detached duplex Lifecamp 1'), ('4 Bedroom SD Lifecamp 1', '4 BD semi detached duplex Lifecamp 1'), ('3 Bedroom T Lifecamp 1', '3 BD Terrace duplex Lifecamp 1'), ('3 Bedroom T Lifecamp 1', '3 BD Terrace duplex Lifecamp 1'), ('250 SQM Lifecamp 2', '250 SQM Lifecamp 2'), ('300 SQM Lifecamp 2', '300 SQM Lifecamp 2'), ('500 SQM Lifecamp 2', '500 SQM Lifecamp 2'), ('750 SQM Lifecamp 2', '500 SQM Lifecamp 2'), ('4 Bedroom FD Lifecamp 2', '4 BD fully detached duplex Lifecamp 2'), ('4 Bedroom SD Lifecamp 2', '4 BD semi detached duplex Lifecamp 2'), ('3 Bedroom T Lifecamp 2', '3 BD Terrace duplex Lifecamp 2'), ('3 Bedroom T Lifecamp 2', '3 BD Terrace duplex Lifecamp 2'), ('250 SQM Katampe Extention', '250 SQM Lifecamp 2'), ('300 SQM Katampe Extention', '300 SQM Lifecamp 2'), ('500 SQM Katampe Extention', '500 SQM Lifecamp 2'), ('750 SQM Katampe Extention', '500 SQM Lifecamp 2'), ('4 Bedroom FD Katampe Extention', '4 BD fully detached duplex Katampe Extention'), ('4 Bedroom SD Katampe Extention', '4 BD semi detached duplex Katampe Extention'), ('3 Bedroom T Katampe Extention', '3 BD Terrace duplex Katampe Extention'), ('3 Bedroom T Katampe Extention', '3 BD Terrace duplex Katampe Extention'), ('250 SQM Karsana', '250 SQM Karsana'), ('300 SQM Karsana', '300 SQM Karsana'), ('500 SQM Karsana', '500 SQM Karsana'), ('750 SQM Karsana', '500 SQM Karsana'), ('4 Bedroom FD Karsana', '4 BD fully detached duplex Karsana'), ('4 Bedroom SD Karsana', '4 BD semi detached duplex Karsana'), ('3 Bedroom T Karsana', '3 BD Terrace duplex Karsana'), ('3 Bedroom T Karsana', '3 BD Terrace duplex Karsana')], max_length=120)),
                ('initial_quantity', models.IntegerField()),
                ('quantity_in_stock', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=130)),
                ('price', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('amount_left', models.IntegerField()),
                ('sales_date', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('agent_comment', models.TextField(max_length=300)),
                ('agent_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sow_app.agent')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sow_app.property')),
            ],
        ),
    ]
